version: '3.8'

services:
  db:
    image: postgres:13
    container_name: tarik_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: tarik_user
      POSTGRES_PASSWORD: tarik_password
      POSTGRES_DB: tarik_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tarik_backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: tarik_user
      DATABASE_PASSWORD: tarik_password
      DATABASE_NAME: tarik_db
      JWT_SECRET: your_jwt_secret_key
      NODE_ENV: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    command: yarn start:dev

volumes:
  postgres-data:
